DFC.Digital/DFC.Digital.Data/Model/ApprenticeVacancy.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Base/DynamicModuleRepository.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/ApprenticeVacancyConverter.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Controllers/JobProfileApprenticeshipsControllerTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Views/JobProfileApprenticeshipViewTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Controllers/JobProfileApprenticeshipsController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Views/JobProfileApprenticeships/Index.cshtml
Url Name Restored to URL .  Search working perfectly fine after reindexing the debug on local enviroment.
=> Url Name Restored as original

DFC.Digital/DFC.Digital.AcceptanceTest/DFC.Digital.AcceptanceTest.csproj, DFC.Digital/DFC.Digital.Service.AzureSearch.IntegrationTests/DFC.Digital.Service.AzureSearch.IntegrationTests.csproj, DFC.Digital/DFC.Digital.Service.AzureSearch.IntegrationTests/app.config.template, DFC.Digital/DFC.Digital.Service.AzureSearch.UnitTests/AzGateway/AzSearchQueryServiceTests.cs
- Added missing feature.cs files generated by specflow
=> Fix build failure

DFC.Digital/DFC.Digital.AcceptanceTest/AcceptanceCriteria/Features/JobProfile.feature, DFC.Digital/DFC.Digital.AcceptanceTest/AcceptanceCriteria/Features/PreSearchFilter.feature, DFC.Digital/DFC.Digital.AcceptanceTest/AcceptanceCriteria/Steps/BaseStep.cs, DFC.Digital/DFC.Digital.AcceptanceTest/AcceptanceCriteria/Steps/JobProfileSteps.cs, DFC.Digital/DFC.Digital.AcceptanceTest/AcceptanceCriteria/Steps/PreSearchFilterSteps.cs, DFC.Digital/DFC.Digital.AcceptanceTest/Infrastructure/Pages/JobProfilePage.cs
Tests have been amended including data / some code to now work across all 4 of our environments.
=> DFC-2703 - Update of AT to work across all environments

DFC.Digital/DFC.Digital.Web.Core/DFC.Digital.Web.Core.csproj, DFC.Digital/DFC.Digital.Web.Core/HtmlExtentions/ReplaceStringTokensExtension.cs, DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_toolkit/MVC/Views/Layouts/default.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_toolkit/MVC/Views/Web.config
Client side tracking in application insights
=> DFC-2811-client side tracking in application insights

DFC.Digital/DFC.Digital.Service.CourseSearch/Converters/MessageConverter.cs
Changed course search to return results by relevance.
=> Changed course search to return results by relevance.

DFC.Digital/DFC.Digital.Azure.Resources/DeploymentHelpers/Cancel-SwapWithPreview.ps1, DFC.Digital/DFC.Digital.Azure.Resources/DeploymentHelpers/Complete-SwapWithPreview.ps1, DFC.Digital/DFC.Digital.Azure.Resources/DeploymentHelpers/Start-SwapWithPreview.ps1
Added 3 files to replace the inline PowerShell in VSTS deployment so we can swap with preview rather than just swap
=> Swap with Preview scripts for VSTS

DFC.Digital/DFC.Digital.Repository.SitefinityCMS.UnitTests/Modules/JobProfileCategoryRepositoryUnitTests.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS.UnitTests/Modules/RelatedClassificationsRepositoryTests.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Base/ITaxonomyManagerExtensions.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Base/ITaxonomyRepository.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Base/TaxonomyRepository.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/ApprenticeVacancyConverter.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/DynamicContentExtensions.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/JobProfileCategoryRepository.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/JobProfileConverter.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/JobProfileRelatedCareerConverter.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/JobProfilesRelatedCareersRepository.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/PreSearchFilterConverter.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/RelatedClassificationsRepository.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/TaxonomyManagerExtensions.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/app.config, DFC.Digital/DFC.Digital.Service.CourseSearch/CourseOpportunityBuilder.cs, DFC.Digital/DFC.Digital.Service.CourseSearchProvider.UnitTests/ManageCourseServiceTests.cs, DFC.Digital/DFC.Digital.Web.Core/HtmlExtentions/ReplaceStringTokensExtension.cs
DFC-3073 - Course search change business rule and remove order by start date.
- Removed order by start date
=> DFC-3073 - Course search change business rule and remove order by start date

DFC.Digital/DFC.Digital.Web.Sitefinity/App_Data/Sitefinity/Configuration/WebServicesConfig.config
This is a pre-requisite for ImportTool.
=> DFC-3668-Added the required content types to the web service api

DFC.Digital/DFC.Digital.Azure.Resources/DeploymentHelpers/Copy-Database.ps1, DFC.Digital/DFC.Digital.Azure.Resources/DeploymentHelpers/Set-SearchIndexName.ps1
Will stop the warning messages during a release
=> Replaced depreciated Find-AzureRmResource with Get-AzureRmResource

DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Views/JobProfileWhatItTakes/DesignerView.Simple.cshtml
Fixed bug with checkbox binding in design view for widget.
Checkboxes were not binding to the model correctly.
=> Fixed bug with checkbox binding in design view for widget.

DFC.Digital/DFC.Digital.Azure.Resources/DeploymentHelpers/Copy-Database.ps1, DFC.Digital/DFC.Digital.Azure.Resources/DeploymentHelpers/Set-SearchIndexName.ps1
Reverts SkillsFundingAgency/dfc-digital#132
=> Revert "Replaced depreciated Find-AzureRmResource with Get-AzureRmResource"

DFC.Digital/DFC.Digital.Web.Sitefinity.Widgets.UnitTests/Controllers/DfcBreadcrumbControllerTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.Widgets/Mvc/Controllers/DfcBreadcrumbController.cs
Also Added tests for code coverage
=> DFC-4270 Updated breadcrumbs to showJP Profile title.

DFC.Digital/DFC.Digital.Azure.Resources/DeploymentHelpers/Copy-Database.ps1, DFC.Digital/DFC.Digital.Azure.Resources/DeploymentHelpers/Set-SearchIndexName.ps1
DFC-3804 When using the Azure PS 6 module (or later) change from using Find-AzureRmResource to Get-AzureRmResource
=> DFC-3804 Update deployment powershell scripts to Azure PS v6

DFC.Digital/DFC.Digital.Azure.Resources/PostDeploymentScripts/Copy-Templates.cmd, DFC.Digital/DFC.Digital.Azure.Resources/PostDeploymentScripts/Copy-Templates.ps1, DFC.Digital/DFC.Digital.Web.Sitefinity/parameters.xml
Added tokenization for sitemap.xml and robots.txt and the ability to deploy different robots.txt files depending upon the environment
=> DFC-4623 DFC-4624 SEO deployment

DFC.Digital/DFC.Digital.Web.Sitefinity/parameters.xml, DFC.Digital/DFC.Digital.Web.Sitefinity/robots.prod.txt.template, DFC.Digital/DFC.Digital.Web.Sitefinity/robots.txt.template, DFC.Digital/DFC.Digital.Web.Sitefinity/sitemap.xml.template
Updated the tokens to ensure correct urls is used based on BG deployment.
=> Changes to token use __baseUrl__ instead of __targetUrl__

DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Views/JobProfileSearchBox/Index.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Views/JobProfileSearchBox/JobProfile.cshtml
=> DFC-4722 - Updated search on home and job profile to meet accessibility requirements

DFC.Digital/DFC.Digital.Web.Sitefinity.Core/Config/AutofacModule.cs
Added the missing type registration to the autofac module.
=> DFC-4917 - Fix for sitemap handler not resolved issue.

DFC.Digital/DFC.Digital.Repository.SitefinityCMS/CMSExtensions/UserRepository.cs
Added null checks when getting user profile.
=> Added null checks when getting user profile

DFC.Digital/DFC.Digital.Web.Sitefinity.CmsExtensions.UnitTests/Controllers/ApprenticeshipVacancyReportControllerTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.CmsExtensions/MVC/Controllers/ApprenticeshipVacancyReportController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.CmsExtensions/MVC/Views/ApprenticeshipVacancyReport/Index.cshtml
Changed column headings and changed frameworks to be pipe delimited.
=> Changed column headings and changed frameworks to be pipe delimited.

DFC.Digital/DFC.Digital.Data/Interfaces/ISearchQueryBuilder.cs, DFC.Digital/DFC.Digital.Service.AzureSearch.UnitTests/DFC.Digital.Service.AzureSearch.UnitTests.csproj, DFC.Digital/DFC.Digital.Service.AzureSearch.UnitTests/DfcBuildExactMatchSearch.cs, DFC.Digital/DFC.Digital.Service.AzureSearch.UnitTests/DfcSearchQueryServiceTests.cs, DFC.Digital/DFC.Digital.Service.AzureSearch/DfcSearchQueryBuilder.cs, DFC.Digital/DFC.Digital.Service.AzureSearch/DfcSearchQueryService.cs
Added searching for exact match when using a phrase.
=> Added searching for exact match when using a phrase

DFC.Digital/DFC.Digital.Web.Sitefinity.CmsExtensions.UnitTests/Controllers/ApprenticeshipVacancyReportControllerTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.CmsExtensions/MVC/Controllers/ApprenticeshipVacancyReportController.cs
Fixed controller to check for nulls when creating view.
=> Fixes for Null SOC codes

DFC.Digital/DFC.Digital.Azure.Resources/Search/template.json
Set replicas as recomendation https://docs.microsoft.com/en-us/azure/search/search-capacity-planning#high-availability
=> DFC-5930 Changed number search replicas to 3

DFC.Digital/DFC.Digital.Azure.Resources/Cosmo DB/config.azcli
Changed TTL to 15 days for cosmos
=> DFC-6421 - Changed TTL to 15 days for cosmos

Resources/Copy-Templates.cmd, Resources/cosmosdb.json, Resources/parameters.json, Resources/template.json
Files used to integrate lab into the dfc-digital repo
=> NCSD-262 lab CI/CD pipleine

Resources/template.json
Securestrings not working in template output, changed to strings
=> NCSD-275 Template strings

Resources/template.json
Changed Redis connection string format to suit Sitefinity
=> NCSD-263 Redis connection string

DFC.Digital/DFC.Digital.Web.Sitefinity/sitemap-old.xml
Changed sitemap-old to include links for help to get a job
=> Changed sitemap-old to add links for Help to get a job

DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_service_toolkit/MVC/Views/Layouts/service_default.cshtml
Added empty placeholder which can be used for breadcrumbs
=> added placeholder for breadcrumb

DFC.Digital/DFC.Digital.Web.Sitefinity.ContactUsModule/Mvc/Controllers/FeedbackController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.ContactUsModule/Mvc/Views/Shared/ErrorSummary.cshtml
- DFC-8225 - Send Multiple Email Recipients (#338 )
- DFC-8560 - Functionality for character count (#339, #346, #350 )
- DFC-8364 - DYSAC updated search index fields (#340 )
- DFC-8436 - SendGrid transient fault handling (#341)
- DFC-8666 - Update to failing tests (#342 )
- Added cookie message to contact us pages (#343)
- DFC-8939 - Mislabeled field fix (#344)
- DFC-8714 - Intermittent build errors (#347)
- DFC-8954 - Contact us fix for char count messaging (#348)
- Fixed styling issue with cookie message (#349)
- DFC-8939-Send-Grid-Labels-Fix (#351)
=> For Release/v1.1.13.1

DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_toolkit/MVC/Views/Layouts/default.cshtml
The URL that we were generating for preview did not match the one implemented in composite preview, This fixes it.
=> Fix paths for composite preview.

DFC.Digital/DFC.Digital.Web.Sitefinity.ContactUsModule/Mvc/Views/ContactAdviser/Index.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity.ContactUsModule/Mvc/Views/Feedback/Index.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity.ContactUsModule/Mvc/Views/SelectOption/Index.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity.ContactUsModule/Mvc/Views/Technical/Index.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity.ContactUsModule/Mvc/Views/YourDetails/ContactAdvisor.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity.ContactUsModule/Mvc/Views/YourDetails/Feedback.cshtml
Introduced targeted forms for validation. Hence a corresponding change in dfc-digital-assets is required https://github.com/SkillsFundingAgency/dfc-digital-assets/pull/55.
=> Added "with-validation-summary" class to forms that should have GDS validation summary.

DFC.Digital/DFC.Digital.Web.Sitefinity/Views/Shared/_govuk_Header.cshtml
Updated the privacy and cookies URL
=> Updated the privacy and cookies URL

DFC.Digital/DFC.Digital.Data/DFC.Digital.Data.csproj, DFC.Digital/DFC.Digital.Data/Model/CompositeUI/JobProfileMessage.cs, DFC.Digital/DFC.Digital.Data/Model/Enum/MessageAction.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/CompositeUI/DynamicContentConverter.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.Core/DataEventHandling/DataEventProcessor.cs
There was an issue with Canonical name showing title instead of URL name. This was updated to URL name now.
=> Updated Canonical name to URL name

DFC.Digital/DFC.Digital.Web.Sitefinity.Core/DataEventHandling/DataEventProcessor.cs
There was an issue with classifications sending multiple messages when "PUBLISHED" instead of a single message for each Jobprofile type. This was resolved by removing the additional loop
=> DFC-10800 Resolved issue related to Multiple messages

DFC.Digital/DFC.Digital.Web.Sitefinity.Core/DataEventHandling/DataEventProcessor.cs
Typo error -- where the Contextualised field was pointing to wrong field Title
=> DFC-10865-Resolved issue with Contextualised field pointing to wrong property

DFC.Digital/DFC.Digital.Data/Model/CompositeUI/MessageModels/ClassificationItem.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.Core/DataEventHandling/DataEventProcessor.cs
I added the previously removed "Description" field which is returning Nulls.
=> Added Description property to the classification items

DFC.Digital/DFC.Digital.Service.CourseSearch/Config/CourseHoursConverter.cs, DFC.Digital/DFC.Digital.Service.CourseSearch/Config/CourseSearchApiAutomapperProfile.cs, DFC.Digital/DFC.Digital.Service.CourseSearch/Config/CourseSearchProviderAutofacModule.cs, DFC.Digital/DFC.Digital.Service.CourseSearch/Config/CourseTypeConverter.cs, DFC.Digital/DFC.Digital.Service.CourseSearch/CourseDirectoryFaCApiService.cs, DFC.Digital/DFC.Digital.Service.CourseSearch/CourseSearchService.cs, DFC.Digital/DFC.Digital.Service.CourseSearch/DFC.Digital.Service.CourseSearchProvider.csproj, DFC.Digital/DFC.Digital.Service.CourseSearch/Utility/CourseSearchLogger.cs, DFC.Digital/DFC.Digital.Service.CourseSearch/packages.config, DFC.Digital/DFC.Digital.Web.Sitefinity/DFC.Digital.Web.Sitefinity.csproj, DFC.Digital/DFC.Digital.Web.Sitefinity/packages.config, DFC.Digital/DFC.Digital.Web.Sitefinity/parameters.xml, DFC.Digital/DFC.Digital.Web.Sitefinity/web.config.template
- Added nuget for FaC client SDK
- Configured to work with existing CS service
=> DFC-11136 - Find a course API client sdk integration to existing CS service

DFC.Digital/DFC.Digital.Data/DFC.Digital.Data.csproj, DFC.Digital/DFC.Digital.Data/Model/CourseDetails.cs, DFC.Digital/DFC.Digital.Data/Model/CourseRegion.cs, DFC.Digital/DFC.Digital.Service.CourseSearch/Config/CourseRegionsConverter.cs, DFC.Digital/DFC.Digital.Service.CourseSearch/Config/CourseSearchApiAutomapperProfile.cs, DFC.Digital/DFC.Digital.Service.CourseSearch/DFC.Digital.Service.CourseSearchProvider.csproj, DFC.Digital/DFC.Digital.Service.CourseSearchProvider.UnitTests/Config/CourseSearchApiAutomapperProfileTests.cs, DFC.Digital/DFC.Digital.Service.CourseSearchProvider.UnitTests/DFC.Digital.Service.CourseSearchProvider.UnitTests.csproj, DFC.Digital/DFC.Digital.Service.CourseSearchProvider.UnitTests/packages.config, DFC.Digital/DFC.Digital.Web.Sitefinity.CourseModule.UnitTests/DFC.Digital.Web.Sitefinity.CourseModule.UnitTests.csproj, DFC.Digital/DFC.Digital.Web.Sitefinity.CourseModule.UnitTests/Views/CourseDetailsWorkBasedVenuesTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.CourseModule/Mvc/Controllers/CourseDetailsController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.CourseModule/Mvc/Models/CourseDetailsViewModel.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.CourseModule/Mvc/Views/CourseDetails/CourseDetails.cshtml
Added views, service and tests to handle workbased venues
=> Added views, service and tests to handle workbased venues

Resources/JobProfileSearchIndexConfig.json
Added the shared configuration json template file that gets tokenized
=> NCSD-2610: Shared configuration

DFC.Digital/DFC.Digital.Web.Sitefinity/web.config.template
Updated Microsoft.Extensions.Primitives to use version 2.2.0.0
=> Updated Microsoft.Extensions.Primitives to use version 2.2.0.0

DFC.Digital/DFC.Digital.Web.Sitefinity/parameters.xml
Escaped (for XML) shared config connection string
=> NCSD-2911: Shared config

DFC.Digital/DFC.Digital.Web.Sitefinity.CourseModule.UnitTests/Views/CourseDetailsViewTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.CourseModule/Mvc/Controllers/CourseDetailsController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.CourseModule/Mvc/Models/CourseDetailsViewModel.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.CourseModule/Mvc/Views/CourseDetails/Provider.cshtml
=> Release v1.1.35.1

DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_service_toolkit/MVC/Views/Layouts/service_default.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_toolkit/MVC/Views/Layouts/default.cshtml
Added call to configureAppInsightsUsage for cookie prefrences
=> Added call to configureAppInsightsUsage for cookie prefrences

DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_service_toolkit/MVC/Views/Layouts/service_default.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_toolkit/MVC/Views/Layouts/default.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity/Views/Shared/_govuk_Header.cshtml
- Updated cookie preferences for AppInsights (#525)
- DFC-12657 - Removed cookie banner (#524)
=> Release v1.1.39.1

DFC.Digital/DFC.Digital.Web.Sitefinity/App_Data/Sitefinity/Configuration/SecurityConfig.config.template
Reverts SkillsFundingAgency/dfc-digital#541
=> Revert "DFC-12883-reverted back password reset functionality"

DFC.Digital/DFC.Digital.Core/Utilities/Constants.cs, DFC.Digital/DFC.Digital.Web.Sitefinity/parameters.xml, DFC.Digital/DFC.Digital.Web.Sitefinity/web.config.template
Added CUI heath check endpoints to config parameters file
=> Added heath check endpoints to parameters file

DFC.Digital/DFC.Digital.Web.Sitefinity/App_Data/Sitefinity/Configuration/WebSecurityConfig.config.template
Removed vibrate feature policy and added sync-xhr
=> Removed vibrate feature policy and added sync-xhr

DFC.Digital/DFC.Digital.Web.Sitefinity.CmsExtensions/Web.config, DFC.Digital/DFC.Digital.Web.Sitefinity.ContactUsModule/Web.config, DFC.Digital/DFC.Digital.Web.Sitefinity/App_Data/Sitefinity/Configuration/WebSecurityConfig.config.template
=> Release v1.1.44.2

DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_service_toolkit/MVC/Views/Layouts/service_default.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_toolkit/MVC/Views/Layouts/default.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity/Views/Shared/_Head.cshtml
Release: alpha0.1 New GTM tag added for troubleshooting.
=> Release: alpha0.1 New GTM tag added for troubleshooting.

DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_service_toolkit/MVC/Views/Layouts/service_default.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_toolkit/MVC/Views/Layouts/default.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity/Views/Shared/_Head.cshtml
Reverts SkillsFundingAgency/dfc-digital#568
=> Revert "Release: alpha0.1 New GTM tag added for troubleshooting."

DFC.Digital/DFC.Digital.AutomationTest.Utilities/SpecflowExtensions.cs, DFC.Digital/DFC.Digital.Data/DFC.Digital.Data.csproj, DFC.Digital/DFC.Digital.Data/Interfaces/IBuildSearchFilterService.cs, DFC.Digital/DFC.Digital.Data/Model/JobProfileIndex.cs, DFC.Digital/DFC.Digital.Data/Model/PreSearchFilterOperator.cs, DFC.Digital/DFC.Digital.Data/Model/PreSearchFilterType.cs, DFC.Digital/DFC.Digital.Data/Model/PsfOnetSkill.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/DFC.Digital.Repository.SitefinityCMS.csproj, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/JobProfileOverloadForSearchConverter.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/PreSearchFilterConverter.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/Modules/PreSearchFilterOnetSkillConverter.cs, DFC.Digital/DFC.Digital.Repository.SitefinityCMS/SitefinityRepositoryAutofacModule.cs, DFC.Digital/DFC.Digital.Service.AzureSearch.UnitTests/DfcBuildFilterServiceTests.cs, DFC.Digital/DFC.Digital.Service.AzureSearch/DfcBuildFilterService.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.DfcSearchModule.UnitTests/SearchIndexEnhancers/JobProfileIndexEnhancerTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.DfcSearchModule/SearchIndexEnhancers/JobProfileIndexEnhancer.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Config/JobProfilesAutoMapperProfileTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Controllers/PreSearchFiltersControllerTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests.csproj, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Views/PreSearchFiltersViewTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Config/JobProfilesAutoMapperProfile.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/DFC.Digital.Web.Sitefinity.JobProfileModule.csproj, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Controllers/PSFSearchController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Controllers/PreSearchFiltersController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Controllers/PsfSearchController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Models/JobProfileSearchResultItemViewModel.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Models/PSFModel.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Models/PsfSearchResultsViewModel.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Views/PreSearchFilters/Index.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Views/PsfSearch/SearchResult.cshtml
=> Pre search filters feature

DFC.Digital/DFC.Digital.AutomationTest.Utilities/SpecflowExtensions.cs, DFC.Digital/DFC.Digital.Data/DFC.Digital.Data.csproj, DFC.Digital/DFC.Digital.Data/Model/JobProfileIndex.cs, DFC.Digital/DFC.Digital.Data/Model/PreSearchFilterType.cs, DFC.Digital/DFC.Digital.Data/Model/PsfCategory.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.DfcSearchModule/SearchIndexEnhancers/JobProfileIndexEnhancer.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Controllers/PreSearchFiltersControllerTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests.csproj, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Views/PreSearchFiltersViewTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Controllers/PreSearchFiltersController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Models/PSFSection.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Views/PreSearchFilters/Index.cshtml
- Make select message configurable (#608) 
- Resolved issue related to Accordion list not saving the option state… (#607)
- Default covid affected to No (#606)
=> Release v1.1.51.2

DFC.Digital/DFC.Digital.Repository.SitefinityCMS/SitefinityRepositoryAutofacModule.cs, DFC.Digital/DFC.Digital.Web.Core/Config/WebCoreAutofacConfig.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Controllers/PreSearchFiltersControllerTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Views/PreSearchFiltersViewTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Controllers/PreSearchFiltersController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Models/PSFModel.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Views/PreSearchFilters/Index.cshtml
Make automapper config single instance
Make Sitefinity dynamic module manager single instance
=> Make automapper config single instance

DFC.Digital/DFC.Digital.Repository.SitefinityCMS/SitefinityRepositoryAutofacModule.cs, DFC.Digital/DFC.Digital.Web.Core/Config/WebCoreAutofacConfig.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Controllers/PreSearchFiltersControllerTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule.UnitTests/Views/PreSearchFiltersViewTests.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/DFC.Digital.Web.Sitefinity.JobProfileModule.csproj, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Controllers/PreSearchFiltersController.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Models/PSFModel.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Models/PsfBack.cs, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Views/PreSearchFilters/Index.cshtml, DFC.Digital/DFC.Digital.Web.Sitefinity.JobProfileModule/Mvc/Views/PsfSearch/SearchResult.cshtml
Make Automapper config single instance (614)
Make Sitefinity dynamic module manager single instance (614)
Make showing of matching profile on each filter page switchable (614)
Removed duplicate Ids on back form in PSF (610)
=> Release v1.1.51.3

DFC.Digital/DFC.Digital.Azure.Resources/Search/parameters.json, DFC.Digital/DFC.Digital.Azure.Resources/Search/template.json
Configured new parameter for Azure Search replica count
=> NCSD-4850 Configured new parameter for Azure Search replica count

DFC.Digital/DFC.Digital.Web.Sitefinity/Global.asax.cs, DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_service_toolkit/GridSystem/Templates/hero-banner.html, DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_service_toolkit/MVC/Views/Layouts/service_default.cshtml
* DFC-13940 updated toolkit for LIVE to national careers toolkit
* Updated changes for toolkit updates for gds_service_toolkit
* Updated all the changes related to gds_service_toolkit updates
=> TASK-DFC-13940-switch-gds_service_toolkit-to-nationalcareers_toolkit

DFC.Digital/DFC.Digital.Web.Sitefinity/ResourcePackages/gds_service_toolkit/GridSystem/Templates/service-header.html
Append govuk to start of module and class, as this version of govuk-frontend requires them
=> TASK-DFC-13940 Switching to latest gds toolkit
